name: Build-Debug

on:
  push:
    branches:
      - "master"
      - "v2.0"
  pull_request:
    branches:
      - "master"
      - "v2.0"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: Cysharp/Actions/.github/actions/setup-dotnet@main
        with:
          dotnet-version: |
            6.0.x
      # build CommandTools first (using dotnet run command in ZLogger.csproj)
      - run: dotnet build -c Debug ./tools/CommandTools/CommandTools.csproj
      - run: dotnet build -c Debug
      - run: dotnet test -c Debug --no-build
